# Generated by Django 2.2.6 on 2019-11-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='language_courses',
            new_name='name',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='snippets.Course'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='snippets.Course'),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[(1, 'Facebook'), (2, 'Phone'), (3, 'Email')], default=True, max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.Category'),
        ),
    ]
